### ISSUE TITLE
Terraform for AWS, GCE, etc

### ISSUE THREAD

**Issue by asim** [micro/kubernetes#1]
Add terraform config so the demo can be deployed on AWS, GCE or anywhere else.

**Comment by surek** [comment]
Hi Asim, I can try to give this a go as I want to deploy to AWS.

**Comment by asim** [comment]
Sounds good! Drop it under the directory `terraform/aws`. I think v1 can be as simple as getting a 3 machines up across up, ideally within a region across AZs. Minimum requirement is running what's in the registry and micro directories for the consul registry and api, web, sidecar.

Let me know your thoughts.

**Comment by surek** [comment]
Yep, it sounds like a good approach. I'll create instances for registry, api and sidecar to start with.

**Comment by asim** [comment]
Cool. Let me know your thoughts on architecture and something like draw.io might be cool to visualise. My last attempt at explaining this looked something like https://blog.micro.mu/assets/images/regions.png.

**Comment by surek** [comment]
Your example shows arrows linking registry/brokers/transport across availability zones. Is that just a logical correlation or are you implying those instances communicate as clusters?

**Comment by asim** [comment]
That is in fact a cluster which allows you to be tolerant to AZ failures. The idea is that you run the identical stack in each AZ with distributed systems bridging the gap for the registry, transport, broker, database, etc. When an AZ goes down the underlying systems should be able to cope with it.

**Comment by surek** [comment]
Right, got it. So I believe this would mean we'd need VPC-peering. Potentially private/public subnets as well. Will confirm, but my aim is to keep it as simple as possible to meet our objectives.
