### ISSUE TITLE
Serviceaccount err

### ISSUE THREAD

**Issue by theobouwman** [micro/kubernetes#3]
I got this error on MacOS:

```
2017/07/28 20:17:51 stat /var/run/secrets/kubernetes.io/serviceaccount: no such file or directory
```

**Comment by asim** [comment]
This is a kubernetes issue. Please google it.

**Comment by scholar-ink** [comment]
@theobouwman  I also have the same problem. How do you solve it?

**Comment by scholar-ink** [comment]
@asim   This problem has not been solved, also checked the Google, can you help to answer it?

**Comment by asim** [comment]
This is completely unrelated to micro. Its a kubernetes issue. Google it and you'll see that it's related to service accounts being created for pods. Please discuss in slack if you need help.

**Comment by hgkmail** [comment]
@scholar-ink 
use following command to prevent this error: 
kubectl run micro -i --tty --rm --restart=Never --image=microhq/micro:kubernetes list services
