### ISSUE TITLE
I get "malformed HTTP response" when use kubenetes plugin,can anyone give me some advice

### ISSUE THREAD

**Issue by Aavon** [micro/kubernetes#4]
I use the micro API to visit service ,it works well on Consul but get "malformed HTTP response" when I migrate them to Kubernetes.

###micro list ###
all the service registered

### micro api ###
i think the micro api works well ,but when client.Call ,the error appeared.And my API service has not been called.

micro/micro/internal/handler/api.go
```go
if err := (*cmd.DefaultOptions().Client).Call(ctx, req, rsp, client.WithSelectOption(so)); err != nil {
//there is the error throwed
```

### Code ###
I used the "github.com/micro/kubernetes/go/micro" to create my service.

### error detail ###
{"id":"go.micro.client.transport","code":500,"detail":"malformed HTTP response \"\\x00\\x00\\x00\\x04\\x00\\x00\\x00\\x00\\x00\"","status":"Internal Server Error"}

### Kubernetes ###
I tried "github.com/micro/kubernetes/run.sh" ,they work well ,So I think kubernetes env is all right.

### Consul ###
i used Consul locally,they work all right.

Can anyone give me some advice....

**Comment by asim** [comment]
Which version of the micro api are you using? If you look at the code for "github.com/micro/kubernetes/go/micro" you'll see it uses grpc so the micro api also needs to use grpc.

**Comment by Aavon** [comment]
@asim 
My micro Version is
---------  **micro version 0.5.0**

I need my API Gateway to provide Restful API to others.And I know I can use Micro to achieve it .So I tried to change the following code in "github.com/micro/kubernetes/go/micro":
```go
// return a micro.Service
return micro.NewService(options...)
``` 

But,the problem appears again.

Now.I guess,is there any TLS issue？Because the "malformed HTTP response" is not nothing in the response,but some garbled.In my memory, I encountered the same phenomenon before, using HTTP protocol to access HTTPS service.

So.what`s you opinion?  And thanks for your reply.

**Comment by asim** [comment]
Look at the code for "github.com/micro/kubernetes/go/micro". This uses not only the kubernetes registry but also grpc. If you are using this then you must also build the micro toolkit from "github.com/micro/kubernetes/cmd/micro" which makes use of the kubernetes registry and grpc.

What's you're seeing is an incompatible message format on the wire. Go-micro and the micro toolkit by default use the http transport and json-rpc or proto-rpc for communication. If you change your go-micro app to use something else then the toolkit must also change.

Please use github.com/micro/kubernetes/go/micro and github.com/micro/kubernetes/cmd/micro together or include the the grpc plugins.

**Comment by Aavon** [comment]
## Amazing! It's really helpful! ##
I have used "github.com/micro/micro/main.go" and plugined the "github.com/micro/go-plugins/registry/kubernetes" ,this can register the service but encounter the problem!
I change the code to "github.com/micro/kubernetes/cmd/micro/main.go" (you updated).It works well!

I think the following code works:
```
client.DefaultClient = cli.NewClient()
server.DefaultServer = srv.NewServer()
```
I do not  use the right client to call the service ,So I get the  incompatible message(like you said ).

Finally,thank you very much!
