### ISSUE TITLE
grpc transport is closing

### ISSUE THREAD

**Issue by andrew-jones** [micro/kubernetes#5]
I've run into an issue after upgrading my micro containers to the latest version.  I've downgraded the micro api container to an older version (~6 weeks old) but left the micro web container as the new one.  So downgrading fixed the issue.

If I submit any RPC request via micro web currently (same error via micro api when running the new image)

`{
  "id": "go.micro.rpc",
  "code": 500,
  "detail": "error during request: transport is closing",
  "status": "Internal Server Error"
}`

I've had a small dig and I think this is coming from the grpc-go lib.  I haven't had a change to go over the commits to micro/micro or micro/kubernetes in the last 6 weeks yet, I will do tomorrow unless any has any ideas on the cause already?

For the record the same thing happens on Kubernetes 1.6.* and 1.8.*.

**Comment by asim** [comment]
Which image and tag are you using? The micro:kubernetes image:tag has changed to use grpc. The default micro:latest image sticks with the defaults of go-micro.

**Comment by andrew-jones** [comment]
I'm using micro:kubernetes and that would be my issue.  Can I configure the micro:kubernetes container via env vars or cli flags to set the default client/server to the go-micro default?  which was rpc?

**Comment by andrew-jones** [comment]
Should have had a look first, for anyone else hitting this issue my new kubernetes configuration looks like this. 

```
command: [
    "/micro",
    "--registry=kubernetes",
    "--register_ttl=60",
    "--register_interval=30",
    "--selector=cache",
    "--client=rpc",
    "--server=rpc",
    "--enable_stats",
    "web",
    "--address=0.0.0.0:8080"
]
```
