### ISSUE TITLE
unable to build k8's greeter example

### ISSUE THREAD

**Issue by jnana-rb** [micro/kubernetes#6]
Following error occurs on build attempt for https://github.com/micro/kubernetes/blob/master/examples/greeter/main.go

```
go build -o k8s-greeter main.go
# github.com/micro/kubernetes/go/micro
../../go/micro/micro.go:29:3: undefined: micro.Selector 
```

**Comment by asim** [comment]
Your go-micro is out of date. Please `go get -u github.com/micro/go-micro`
