### ISSUE TITLE
Demo issues

### ISSUE THREAD

**Issue by jnana-rb** [micro/kubernetes#7]
Steps followed

- go get github.com/micro/kubernetes
- cd $GOPATH/micro/kubernetes
- ./scripts/run.sh start
- set-up a minikube host.

```
kubernetes jkagati$ kubectl get svc
NAME           TYPE           CLUSTER-IP      EXTERNAL-IP   PORT(S)          AGE
greeter1-web   NodePort       10.96.205.228   <none>        8888:30474/TCP   3h
kubernetes     ClusterIP      10.96.0.1       <none>        443/TCP          8d
micro-api      LoadBalancer   10.105.63.69    <pending>     80:30152/TCP     35m
micro-car      LoadBalancer   10.108.33.17    <pending>     80:32050/TCP     35m
micro-web      LoadBalancer   10.109.126.34   <pending>     80:31700/TCP     35m
```

```
kubernetes jkagati$ kubectl get pods
NAME                                   READY     STATUS             RESTARTS   AGE
greeter-api-76f759868b-mqvfx           1/1       Running            0          35m
greeter-d5ccd5c7c-85d52                2/2       Running            0          35m
greeter-web-56df85bf6f-wwrwp           1/1       Running            0          35mmicro-api-5bc9548446-cljx6             1/1       Running            0          35m
micro-bot-7b5cfc6fbb-b6zqf             0/1       CrashLoopBackOff   11         35m
micro-car-6bdd59c48f-blj6j             1/1       Running            0          35m
micro-web-679bcf5dfc-qzr8l             1/1       Running            0          35m
node-container-big-sibling-all-jpchj   1/1       Running            0          1h
```

issue :

![screen shot 2018-02-09 at 3 13 51 pm](https://user-images.githubusercontent.com/30687610/36021478-e8efe512-0dab-11e8-88d3-abd188ba39cc.png)

`micro query greeter Say.Hello '{"name":"test"}'` doesn't return with any response.

**Comment by asim** [comment]
Try chrome inspector to see if there's any console output

**Comment by jnana-rb** [comment]
following request works 
` query greeter Say.Hello {"name":"test"} `

Usually by default the `transport` of micro application is `http` and `server` is `rpc` as below

![screen shot 2018-02-12 at 10 41 18 am](https://user-images.githubusercontent.com/30687610/36084238-57e0545c-0fe1-11e8-908b-14c54b7a7cbf.png)

where as in the kubernetes demo `transport` and `server` both are `grpc`.

Is it because of these changes the request structure is changed?

![screen shot 2018-02-12 at 10 39 06 am](https://user-images.githubusercontent.com/30687610/36084277-c591ede4-0fe1-11e8-8826-7d1717ca2fc9.png)

**Comment by asim** [comment]
Your screen shot is demonstrating that you get a response at some point, which indicates there's some sort of transient error. As mentioned. Can you please open the chrome inspector and see what the result of the call is. Any command on the terminal is sent through as a http call.

**Comment by asim** [comment]
I'm running this test with minikube right now and it works perfectly. Your issue appears to be a transient one. Please join the slack if you want to debug further.
