### ISSUE TITLE
rebuild docker image: microhq/micro:kubernetes

### ISSUE THREAD

**Issue by theophanous** [micro/kubernetes#8]
When running the microhq/micro:kubernetes docker image on kubernetes I'm getting CrashLoopBackOff's and the following 

$ kubectl logs micro-web-d4fd7f8c4-w85nx
2018/03/10 18:54:57 Listening on [::]:8082
2018/03/10 18:54:57 Listening on [::]:34832
2018/03/10 18:54:57 Broker Listening on [::]:35816
2018/03/10 18:54:57 No private IP address found, and explicit IP not provided

I believe this has already been fixed in the repo [e8172d4341999adf736fdffa36bf86b8cc68ee11](https://github.com/micro/misc/commit/e8172d4341999adf736fdffa36bf86b8cc68ee11) but the docker image predates the fix, is it possible to rebuild the image to incorporate the fix.

Thanks

**Comment by asim** [comment]
Built and pushed

**Comment by theophanous** [comment]
cheers, seems to have done the trick
